### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by alt3rmann** [dreddsa5dies/urlScrub#1]
Запускаю скрипт. 

Результат: 

> MacBook-Pro:urlScrub user$ go run urlScrub.go
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> main.searchURL(0xc000155140, 0x30, 0xc0000ac030, 0xc00009c018)
> 	/Users/user/urlScrub/urlScrub.go:201 +0xfb7
> main.main()
> 	/Users/user/urlScrub/urlScrub.go:127 +0x8f0
> exit status 2

В логах: 
![image](https://user-images.githubusercontent.com/6911130/57195131-bc176b00-6f57-11e9-9626-72ebe342a593.png)

Скрипт еще живой? Что может быть не так? 
Спасибо!

**Comment by dreddsa5dies** [comment]
Скрипт был для парcинга сайта 2х летней давности. Ещё надо разбираться?

**Comment by alt3rmann** [comment]
Скрипт очень полезный, было бы круто, если бы он заработал, но не критично. Так что от Вашего времени и желания зависит...

**Comment by dreddsa5dies** [comment]
Хорошо, посмотрю на днях.
В то же время советую обратить внимание на [огрн онлайн](https://ogrn.site/)

**Comment by dreddsa5dies** [comment]
[Rectification issue](https://github.com/dreddsa5dies/urlScrub/commit/ebe9723e7cdc026a2bce128c5387dcb9d10baabc)
